// Copyright  All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/lichenglife/miniblog. The professional
// version of this repository is https://github.com/lichenglife/onex.

// MiniBlog API 定义，包含健康检查、用户管理和文章管理的 RPC 接口

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.4
// source: pkg/api/apiserver/v1/apiserver.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pkg_api_apiserver_v1_apiserver_proto protoreflect.FileDescriptor

const file_pkg_api_apiserver_v1_apiserver_proto_rawDesc = "" +
	"\n" +
	"$pkg/api/apiserver/v1/apiserver.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\"pkg/api/apiserver/v1/healthz.proto\x1a\x1fpkg/api/apiserver/v1/post.proto\x1a\x1fpkg/api/apiserver/v1/user.proto\x1a\x1cgoogle/api/annotations.proto2\xe9\t\n" +
	"\bEasyblog\x12O\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x13.v1.HealthzResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/healthz\x12F\n" +
	"\x05Login\x12\x10.v1.LoginRequest\x1a\x11.v1.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12c\n" +
	"\fRefreshToken\x12\x17.v1.RefreshTokenRequest\x1a\x18.v1.RefreshTokenResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/refresh-token\x12s\n" +
	"\x0eChangePassword\x12\x19.v1.ChangePasswordRequest\x1a\x1a.v1.ChangePasswordResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/users/{userID}/password\x12U\n" +
	"\n" +
	"CreateUser\x12\x15.v1.CreateUserRequest\x1a\x16.v1.CreateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12^\n" +
	"\n" +
	"UpdateUser\x12\x15.v1.UpdateUserRequest\x1a\x16.v1.UpdateUserResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/users/{userID}\x12[\n" +
	"\n" +
	"DeleteUser\x12\x15.v1.DeleteUserRequest\x1a\x16.v1.DeleteUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/users/{userID}\x12R\n" +
	"\aGetUser\x12\x12.v1.GetUserRequest\x1a\x13.v1.GetUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/users/{userID}\x12L\n" +
	"\bListUser\x12\x13.v1.ListUserRequest\x1a\x14.v1.ListUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12U\n" +
	"\n" +
	"CreatePost\x12\x15.v1.CreatePostRequest\x1a\x16.v1.CreatePostResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/posts\x12^\n" +
	"\n" +
	"UpdatePost\x12\x15.v1.UpdatePostRequest\x1a\x16.v1.UpdatePostResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/posts/{postID}\x12[\n" +
	"\n" +
	"DeletePost\x12\x15.v1.DeletePostRequest\x1a\x16.v1.DeletePostResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/posts/{postID}\x12R\n" +
	"\aGetPost\x12\x12.v1.GetPostRequest\x1a\x13.v1.GetPostResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/posts/{postID}\x12L\n" +
	"\bListPost\x12\x13.v1.ListPostRequest\x1a\x14.v1.ListPostResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/postsB9Z7github.com/lichenglife/easyblog/pkg/api/apiserver/v1;v1b\x06proto3"

var file_pkg_api_apiserver_v1_apiserver_proto_goTypes = []any{
	(*emptypb.Empty)(nil),          // 0: google.protobuf.Empty
	(*LoginRequest)(nil),           // 1: v1.LoginRequest
	(*RefreshTokenRequest)(nil),    // 2: v1.RefreshTokenRequest
	(*ChangePasswordRequest)(nil),  // 3: v1.ChangePasswordRequest
	(*CreateUserRequest)(nil),      // 4: v1.CreateUserRequest
	(*UpdateUserRequest)(nil),      // 5: v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),      // 6: v1.DeleteUserRequest
	(*GetUserRequest)(nil),         // 7: v1.GetUserRequest
	(*ListUserRequest)(nil),        // 8: v1.ListUserRequest
	(*CreatePostRequest)(nil),      // 9: v1.CreatePostRequest
	(*UpdatePostRequest)(nil),      // 10: v1.UpdatePostRequest
	(*DeletePostRequest)(nil),      // 11: v1.DeletePostRequest
	(*GetPostRequest)(nil),         // 12: v1.GetPostRequest
	(*ListPostRequest)(nil),        // 13: v1.ListPostRequest
	(*HealthzResponse)(nil),        // 14: v1.HealthzResponse
	(*LoginResponse)(nil),          // 15: v1.LoginResponse
	(*RefreshTokenResponse)(nil),   // 16: v1.RefreshTokenResponse
	(*ChangePasswordResponse)(nil), // 17: v1.ChangePasswordResponse
	(*CreateUserResponse)(nil),     // 18: v1.CreateUserResponse
	(*UpdateUserResponse)(nil),     // 19: v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),     // 20: v1.DeleteUserResponse
	(*GetUserResponse)(nil),        // 21: v1.GetUserResponse
	(*ListUserResponse)(nil),       // 22: v1.ListUserResponse
	(*CreatePostResponse)(nil),     // 23: v1.CreatePostResponse
	(*UpdatePostResponse)(nil),     // 24: v1.UpdatePostResponse
	(*DeletePostResponse)(nil),     // 25: v1.DeletePostResponse
	(*GetPostResponse)(nil),        // 26: v1.GetPostResponse
	(*ListPostResponse)(nil),       // 27: v1.ListPostResponse
}
var file_pkg_api_apiserver_v1_apiserver_proto_depIdxs = []int32{
	0,  // 0: v1.Easyblog.Healthz:input_type -> google.protobuf.Empty
	1,  // 1: v1.Easyblog.Login:input_type -> v1.LoginRequest
	2,  // 2: v1.Easyblog.RefreshToken:input_type -> v1.RefreshTokenRequest
	3,  // 3: v1.Easyblog.ChangePassword:input_type -> v1.ChangePasswordRequest
	4,  // 4: v1.Easyblog.CreateUser:input_type -> v1.CreateUserRequest
	5,  // 5: v1.Easyblog.UpdateUser:input_type -> v1.UpdateUserRequest
	6,  // 6: v1.Easyblog.DeleteUser:input_type -> v1.DeleteUserRequest
	7,  // 7: v1.Easyblog.GetUser:input_type -> v1.GetUserRequest
	8,  // 8: v1.Easyblog.ListUser:input_type -> v1.ListUserRequest
	9,  // 9: v1.Easyblog.CreatePost:input_type -> v1.CreatePostRequest
	10, // 10: v1.Easyblog.UpdatePost:input_type -> v1.UpdatePostRequest
	11, // 11: v1.Easyblog.DeletePost:input_type -> v1.DeletePostRequest
	12, // 12: v1.Easyblog.GetPost:input_type -> v1.GetPostRequest
	13, // 13: v1.Easyblog.ListPost:input_type -> v1.ListPostRequest
	14, // 14: v1.Easyblog.Healthz:output_type -> v1.HealthzResponse
	15, // 15: v1.Easyblog.Login:output_type -> v1.LoginResponse
	16, // 16: v1.Easyblog.RefreshToken:output_type -> v1.RefreshTokenResponse
	17, // 17: v1.Easyblog.ChangePassword:output_type -> v1.ChangePasswordResponse
	18, // 18: v1.Easyblog.CreateUser:output_type -> v1.CreateUserResponse
	19, // 19: v1.Easyblog.UpdateUser:output_type -> v1.UpdateUserResponse
	20, // 20: v1.Easyblog.DeleteUser:output_type -> v1.DeleteUserResponse
	21, // 21: v1.Easyblog.GetUser:output_type -> v1.GetUserResponse
	22, // 22: v1.Easyblog.ListUser:output_type -> v1.ListUserResponse
	23, // 23: v1.Easyblog.CreatePost:output_type -> v1.CreatePostResponse
	24, // 24: v1.Easyblog.UpdatePost:output_type -> v1.UpdatePostResponse
	25, // 25: v1.Easyblog.DeletePost:output_type -> v1.DeletePostResponse
	26, // 26: v1.Easyblog.GetPost:output_type -> v1.GetPostResponse
	27, // 27: v1.Easyblog.ListPost:output_type -> v1.ListPostResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_apiserver_v1_apiserver_proto_init() }
func file_pkg_api_apiserver_v1_apiserver_proto_init() {
	if File_pkg_api_apiserver_v1_apiserver_proto != nil {
		return
	}
	file_pkg_api_apiserver_v1_healthz_proto_init()
	file_pkg_api_apiserver_v1_post_proto_init()
	file_pkg_api_apiserver_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_apiserver_v1_apiserver_proto_rawDesc), len(file_pkg_api_apiserver_v1_apiserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_apiserver_v1_apiserver_proto_goTypes,
		DependencyIndexes: file_pkg_api_apiserver_v1_apiserver_proto_depIdxs,
	}.Build()
	File_pkg_api_apiserver_v1_apiserver_proto = out.File
	file_pkg_api_apiserver_v1_apiserver_proto_goTypes = nil
	file_pkg_api_apiserver_v1_apiserver_proto_depIdxs = nil
}
